# Generated by Django 5.2.4 on 2025-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
